// Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Pay.Service.StoreRequest.Client.Models
{
    using Lykke.Pay;
    using Lykke.Pay.Service;
    using Lykke.Pay.Service.StoreRequest;
    using Lykke.Pay.Service.StoreRequest.Client;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class IPayFee
    {
        /// <summary>
        /// Initializes a new instance of the IPayFee class.
        /// </summary>
        public IPayFee()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IPayFee class.
        /// </summary>
        public IPayFee(double? percent = default(double?), int? pips = default(int?), double? fixedFee = default(double?))
        {
            Percent = percent;
            Pips = pips;
            FixedFee = fixedFee;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "percent")]
        public double? Percent { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pips")]
        public int? Pips { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fixedFee")]
        public double? FixedFee { get; set; }

    }
}
