// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Pay.Service.StoreRequest.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OrderRequest
    {
        /// <summary>
        /// Initializes a new instance of the OrderRequest class.
        /// </summary>
        public OrderRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OrderRequest class.
        /// </summary>
        /// <param name="merchantPayRequestStatus">Possible values include:
        /// 'New', 'InProgress', 'Failed', 'Completed'</param>
        /// <param name="merchantPayRequestNotification">Possible values
        /// include: 'Nothing', 'InProgress', 'Success', 'Error'</param>
        public OrderRequest(string merchantId = default(string), string requestId = default(string), string transactionId = default(string), PayFee markup = default(PayFee), string merchantPayRequestStatus = default(string), string merchantPayRequestNotification = default(string), string sourceAddress = default(string), string assetPair = default(string), string exchangeAssetId = default(string), double? amount = default(double?), double? exchangeRate = default(double?), string assetId = default(string), string successUrl = default(string), string errorUrl = default(string), string progressUrl = default(string), string orderId = default(string), string transactionDetectionTime = default(string), string transactionWaitingTime = default(string))
        {
            MerchantId = merchantId;
            RequestId = requestId;
            TransactionId = transactionId;
            Markup = markup;
            MerchantPayRequestStatus = merchantPayRequestStatus;
            MerchantPayRequestNotification = merchantPayRequestNotification;
            SourceAddress = sourceAddress;
            AssetPair = assetPair;
            ExchangeAssetId = exchangeAssetId;
            Amount = amount;
            ExchangeRate = exchangeRate;
            AssetId = assetId;
            SuccessUrl = successUrl;
            ErrorUrl = errorUrl;
            ProgressUrl = progressUrl;
            OrderId = orderId;
            TransactionDetectionTime = transactionDetectionTime;
            TransactionWaitingTime = transactionWaitingTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "merchantId")]
        public string MerchantId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requestId")]
        public string RequestId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transactionId")]
        public string TransactionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "markup")]
        public PayFee Markup { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'New', 'InProgress',
        /// 'Failed', 'Completed'
        /// </summary>
        [JsonProperty(PropertyName = "merchantPayRequestStatus")]
        public string MerchantPayRequestStatus { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Nothing', 'InProgress',
        /// 'Success', 'Error'
        /// </summary>
        [JsonProperty(PropertyName = "merchantPayRequestNotification")]
        public string MerchantPayRequestNotification { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sourceAddress")]
        public string SourceAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assetPair")]
        public string AssetPair { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "exchangeAssetId")]
        public string ExchangeAssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "amount")]
        public double? Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "exchangeRate")]
        public double? ExchangeRate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assetId")]
        public string AssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "successUrl")]
        public string SuccessUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorUrl")]
        public string ErrorUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "progressUrl")]
        public string ProgressUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderId")]
        public string OrderId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transactionDetectionTime")]
        public string TransactionDetectionTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transactionWaitingTime")]
        public string TransactionWaitingTime { get; set; }

    }
}
