// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Pay.Service.StoreRequest.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PayFee
    {
        /// <summary>
        /// Initializes a new instance of the PayFee class.
        /// </summary>
        public PayFee()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PayFee class.
        /// </summary>
        public PayFee(double? percent = default(double?), int? pips = default(int?), double? fixedFee = default(double?))
        {
            Percent = percent;
            Pips = pips;
            FixedFee = fixedFee;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "percent")]
        public double? Percent { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pips")]
        public int? Pips { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fixedFee")]
        public double? FixedFee { get; set; }

    }
}
