// Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Bitcoint.Api.Client.Models
{
    using Bitcoint.Api;
    using Bitcoint.Api.Client;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CreateChannelModel
    {
        /// <summary>
        /// Initializes a new instance of the CreateChannelModel class.
        /// </summary>
        public CreateChannelModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateChannelModel class.
        /// </summary>
        public CreateChannelModel(string clientPubKey = default(string), string hotWalletAddress = default(string), decimal? hubAmount = default(decimal?), string asset = default(string), bool? requiredOperation = default(bool?), System.Guid? transferId = default(System.Guid?))
        {
            ClientPubKey = clientPubKey;
            HotWalletAddress = hotWalletAddress;
            HubAmount = hubAmount;
            Asset = asset;
            RequiredOperation = requiredOperation;
            TransferId = transferId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clientPubKey")]
        public string ClientPubKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hotWalletAddress")]
        public string HotWalletAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hubAmount")]
        public decimal? HubAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "asset")]
        public string Asset { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requiredOperation")]
        public bool? RequiredOperation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transferId")]
        public System.Guid? TransferId { get; set; }

    }
}
