// Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Bitcoint.Api.Client.Models
{
    using Bitcoint.Api;
    using Bitcoint.Api.Client;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CreateCashinModel
    {
        /// <summary>
        /// Initializes a new instance of the CreateCashinModel class.
        /// </summary>
        public CreateCashinModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateCashinModel class.
        /// </summary>
        public CreateCashinModel(string clientPubKey = default(string), string cashinAddress = default(string), decimal? amount = default(decimal?), string asset = default(string), System.Guid? transferId = default(System.Guid?))
        {
            ClientPubKey = clientPubKey;
            CashinAddress = cashinAddress;
            Amount = amount;
            Asset = asset;
            TransferId = transferId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clientPubKey")]
        public string ClientPubKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cashinAddress")]
        public string CashinAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "amount")]
        public decimal? Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "asset")]
        public string Asset { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transferId")]
        public System.Guid? TransferId { get; set; }

    }
}
