// Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Bitcoint.Api.Client.Models
{
    using Bitcoint.Api;
    using Bitcoint.Api.Client;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class OffchainCommitmentsOfChannelResponse
    {
        /// <summary>
        /// Initializes a new instance of the
        /// OffchainCommitmentsOfChannelResponse class.
        /// </summary>
        public OffchainCommitmentsOfChannelResponse()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// OffchainCommitmentsOfChannelResponse class.
        /// </summary>
        public OffchainCommitmentsOfChannelResponse(IList<OffchainCommitmentInfo> commitments = default(IList<OffchainCommitmentInfo>))
        {
            Commitments = commitments;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "commitments")]
        public IList<OffchainCommitmentInfo> Commitments { get; set; }

    }
}
