// Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Pay.Service.GenerateAddress.Client.Models
{
    using Lykke.Pay;
    using Lykke.Pay.Service;
    using Lykke.Pay.Service.GenerateAddress;
    using Lykke.Pay.Service.GenerateAddress.Client;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GenerateAddressRequest
    {
        /// <summary>
        /// Initializes a new instance of the GenerateAddressRequest class.
        /// </summary>
        public GenerateAddressRequest()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GenerateAddressRequest class.
        /// </summary>
        public GenerateAddressRequest(string merchantId = default(string), string assertId = default(string))
        {
            MerchantId = merchantId;
            AssertId = assertId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "merchantId")]
        public string MerchantId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assertId")]
        public string AssertId { get; set; }

    }
}
