// Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Pay.Service.GenerateAddress.Client.Models
{
    using Lykke.Pay;
    using Lykke.Pay.Service;
    using Lykke.Pay.Service.GenerateAddress;
    using Lykke.Pay.Service.GenerateAddress.Client;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GenerateAddressModel
    {
        /// <summary>
        /// Initializes a new instance of the GenerateAddressModel class.
        /// </summary>
        public GenerateAddressModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GenerateAddressModel class.
        /// </summary>
        public GenerateAddressModel(string address = default(string))
        {
            Address = address;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public string Address { get; set; }

    }
}
