// Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Pay.Service.GenerateAddress.Client.Models
{
    using Lykke.Pay;
    using Lykke.Pay.Service;
    using Lykke.Pay.Service.GenerateAddress;
    using Lykke.Pay.Service.GenerateAddress.Client;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class WallerChangeRequest
    {
        /// <summary>
        /// Initializes a new instance of the WallerChangeRequest class.
        /// </summary>
        public WallerChangeRequest()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the WallerChangeRequest class.
        /// </summary>
        public WallerChangeRequest(string walletAddress = default(string), double? deltaAmount = default(double?), string assert = default(string))
        {
            WalletAddress = walletAddress;
            DeltaAmount = deltaAmount;
            Assert = assert;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "walletAddress")]
        public string WalletAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deltaAmount")]
        public double? DeltaAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assert")]
        public string Assert { get; set; }

    }
}
